# Generated by Django 3.2.4 on 2022-01-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220102_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='accounts_ptr',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
