# Generated by Django 3.2.4 on 2022-02-03 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankaccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_account_name', models.CharField(max_length=30)),
                ('bank_account_type', models.CharField(max_length=30)),
                ('user_bvn', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('bank_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
